### ISSUE TITLE
itango 0.1.5 not compatible with PyTango 8.1

### ISSUE THREAD

**Issue by jkotan** [tango-cs/itango#8] opened 2016-09-20 11:14 UTC
Hi,

when we install itango-0.1.5 via setup.py it creates the itango script in the bin directory. A similar itango script in the same location is provided by pytango 8 (python-pytango-8.1.7 on debian). So if we want to install both one overwrites another.

At DESY we cannot create packages without modifiying setup.py of itango, i.e. removing the script creation part. Otherwise debian packages would be not compatible.

On the other hand in setup.py of itango it is written that it should be compatible with PyTango 8.

Bests,
Jan

**Comment by vxgmichel** [comment] 2016-09-20 11:36
Hi Jan,

The pytango 8 compatibility has only been added so that sardana 2.1.0 can support both tango 8 and tango 9. Also, this conflict between the script files is not a problem if the packages are installed using pip. For the official debian release, the requirement for itango will be `pytango >= 9.2.0` to avoid this conflict. More information about that in PR #4.

Does that help you solve your problem?

**Comment by jkotan** [comment] 2016-09-20 11:54
Not really. For me it is like a mess. Depending which package you install  the last its version of `itango`  script is installed which should not be the case. It does not look OK with PEP8. 

So you mean that you drop support for setup.py ?

**Comment by vxgmichel** [comment] 2016-09-20 12:25
> For me it is like a mess. 

It is a bit of a mess and I don't see a good way around it. However, this is a transition thing. 

My recommendation would be to either work with one of those two configurations:
- tango 8 - pytango 8 - sardana 2.0
- tango 9 - pytango 9 - itango - sardana 2.1

Again, it is possible to get sardana 2.1 to work with tango 8, but you'll have to solve this conflict yourself. Either by:
- installing sardana and itango with pip
- or packaging itango with a special rule to remove the `itango` and `itango-qt` scripts.

> Depending which package you install the last its version of itango script is installed which should not be the case

It shouldn't matter since they're both a short cut to the same functionality.

> It does not look OK with PEP8. 

What does PEP8 have to do with that?

> So you mean that you drop support for setup.py ?

I'm not sure to understand what you meant.

However, there might be a cleaner solution to this issue. Let me know if you come up with something more convenient.

**Comment by jkotan** [comment] 2016-09-20 13:17
What about:

    diff --git a/setup.py b/setup.py
    index 9f8de9a..64f3385 100644
    --- a/setup.py
    +++ b/setup.py
    @@ -7,9 +7,13 @@ from setuptools import setup, find_packages
     def get_entry_points():
         major = int(platform.python_version_tuple()[0])
         name = 'itango3' if major == 3 else 'itango'
    -    return {
    -        "console_scripts": ["{0} = itango:run".format(name)],
    -        "gui_scripts": ["{0}-qt = itango:run_qt".format(name)]}
    +    try:
    +        import tango
    +        return {
    +            "console_scripts": ["{0} = itango:run".format(name)],
    +            "gui_scripts": ["{0}-qt = itango:run_qt".format(name)]}
    +    except ImportError:
    +        return {}

**Comment by vxgmichel** [comment] 2016-09-20 13:27
This would require pytango to be installed when the package is being built, which is not something we want.

**Comment by jkotan** [comment] 2016-09-20 13:48
So one can do it other way round:

    diff --git a/setup.py b/setup.py
    index 9f8de9a..9885467 100644
    --- a/setup.py
    +++ b/setup.py
    @@ -7,9 +7,19 @@ from setuptools import setup, find_packages
     def get_entry_points():
         major = int(platform.python_version_tuple()[0])
         name = 'itango3' if major == 3 else 'itango'
    -    return {
    -        "console_scripts": ["{0} = itango:run".format(name)],
    -        "gui_scripts": ["{0}-qt = itango:run_qt".format(name)]}
    +    try:
    +        import tango
    +        return {
    +            "console_scripts": ["{0} = itango:run".format(name)],
    +            "gui_scripts": ["{0}-qt = itango:run_qt".format(name)]}
    +    except ImportError:
    +        try:
    +            import PyTango
    +            return {}
    +        except ImportError:
    +            return {
    +                "console_scripts": ["{0} = itango:run".format(name)],
    +                "gui_scripts": ["{0}-qt = itango:run_qt".format(name)]}

then for PyTango 9 logic is not changed and for PyTango 8 one has to have pytango installed (but you don't care :) ).

**Comment by vxgmichel** [comment] 2016-09-20 14:16
I'm not fond of this solution either, it seems a bit hackish. What about using `-no-pythonX-scripts`?

    python setup.py --command-packages=stdeb.command \
        sdist_dsc --no-python2-scripts=True bdist_deb

Or, in `setup.cfg`:

    [sdist_dsc]
    no-python2-scripts: True
    no-python3-scripts: True

**Comment by jkotan** [comment] 2016-09-20 14:21
python setup.py --command-packages=stdeb.command \
        sdist_dsc --no-python2-scripts=True bdist_deb

does not work with `git-buildpackage`

    [sdist_dsc]
    no-python2-scripts: True
    no-python3-scripts: True

requires changing sources anyhow.

**Comment by vxgmichel** [comment] 2016-09-20 14:52
`git-buildpackage` does use `stdeb` so this should work:

    python setup.py --command-packages=stdeb.command debianize --no-python2-scripts=True

You might have to upgrade `stdeb` though, but it works for me with version 0.8.5.

**Comment by jkotan** [comment] 2016-09-21 05:41
Hi Vincent,

Yes. In principle yes. One can do a tricks, i.e. adding options to setup.py or changing the sources (what we are doing at DESY) by in my opinion it should be fixed in the sources.
If not it should be explicitly explain the installation procedure of itango for pytango 8 e.g. in README.rst, i.e. that itango overrides pytango 8 and therefore one has to install itango without scripts. 

The current situation is really misleading.

Cheers,
Jan

**Comment by vxgmichel** [comment] 2016-09-21 08:12
> One can do a tricks, i.e. adding options to setup.py or changing the sources (what we are doing at DESY) by in my opinion it should be fixed in the sources

Changing the sources is indeed a trick, but adding command line arguments is not. It's a very standard way of customizing an installation/packaging. It cannot be fixed in the sources automatically, since there's no way to know in advance if the package is going to be installed with pytango 8 or pytango 9 (as far as I can tell). Which is why explicit tags looks like the best solution to me.

> It should be explicitly explain the installation procedure of itango for pytango 8 e.g. in README.rst

I agree, the readme file should address this issue. I'll add a section soon, but feel free to make a pull request if you feel like the documentation can be improved :wink:

**Comment by jkotan** [comment] 2016-09-21 08:36
For me , the cleanest option would be to have the separate git branch for PyTango 8 and lower (without scirpts with versioning 0.X.Y) and the other git branch for PyTango 9 and higher (with scripts with versioning  1.X.Y).  Since you are using git merging one line is not a problem in maintaining.

**Comment by vxgmichel** [comment] 2016-09-21 11:27
Hum, you have a point. Would [that](https://github.com/tango-cs/itango/tree/tango8) work for you? If it's OK, I can make a `v0.0.1` tag and a pypi release. In this case I would also drop the support for pytango 8 and ipython 0.10 in the next `v0.1.6` release.

**Comment by jkotan** [comment] 2016-09-21 11:56
The tango8 branch is ok for me (I dont know how about it Zibi and sardana version requirements). 
However its content is wrong. It does not work with sardana. 
Why you have removed `itango` package.
For me it is  enough to remove one line of setup.py from the master branch i.e.

        entry_points=get_entry_points(),

Bests,
Jan

**Comment by vxgmichel** [comment] 2016-09-21 12:07
> Why you have removed itango package?

Because the modules already exist in the pytango 8 package

> It does not work with sardana. 

Could you paste the traceback please?

**Comment by jkotan** [comment] 2016-09-21 12:24
Sorry. You are right. I had some interference with the previous version.

**Comment by reszelaz** [comment] 2016-09-21 16:20
I have performed some simple tests with the tango8 branch and Sardana and everything looks ok from the functional point of view. With that, in Sardana, we would need to change the requirements to: `'PyTango (>=7.2.3)'` and `'itango (>=0.0.1)'`. Apart of that we will recommend in the installation guide that the recommended dependencies versions are, for PyTango < 9 the itango >= 0.0.1, < 0.1.0 and for PyTango > 9 the itango >= 0.1.6. Not following this guide will still be functional, cause the backwards compatibility is still present in the 0.1.6, but could cause the scripts being overwritten.

Just one thing is not clear to me. I have done the following:
1. Created source package of itango from the tango8 branch: `python setup.py sdist`.
2. Installed from it using: `PYTHONPATH=/tmp/kk/lib/python2.7/site-packages/:$PYTHONPATH python setup.py install --prefix=/tmp/kk`
As the result it installs the following script: `/tmp/kk/bin/itango`. Why is that? And isn't it a problem?

**Comment by vxgmichel** [comment] 2016-09-21 16:27
> As the result it installs the following script: `/tmp/kk/bin/itango`

I ran your commands and it worked fine for me, `/tmp/kk/bin/itango` does not exist.

**Comment by reszelaz** [comment] 2016-09-21 16:32
I will check it with docker, my environment must be contaminated:)

**Comment by reszelaz** [comment] 2016-09-21 17:26
You are right, I could not reproduce it in a clean environment. Forget about it..

**Comment by vxgmichel** [comment] 2016-09-22 08:52
@reszelaz @jkotan 
I just pushed to the following branches:
- [tango8](https://github.com/tango-cs/itango/tree/tango8): `itango-0.0.1`requires `IPython>=0.10,<5` and `PyTango>=7.2,<9`
- [drop-compat](https://github.com/tango-cs/itango/tree/drop-compat): `itango-0.1.6` requires `IPython>=1.0` and `pytango>=9.2.0`

Is this setup OK with you?

**Comment by jkotan** [comment] 2016-09-22 09:03
Thanks. Perfect.

**Comment by reszelaz** [comment] 2016-09-22 09:38
@reszelaz commented:
> Apart of that we will recommend in the installation guide that the recommended dependencies versions are, for PyTango < 9 the itango >= 0.0.1, < 0.1.0 and for PyTango > 9 the itango >= 0.1.6. Not following this guide will still be functional, because the backwards compatibility is still present in the 0.1.6, but could cause the scripts being overwritten.

This won't be true, since you are dropping the support. Hence not following this recommendation won't be functional. But this is also ok.

@vxgmichel when do you plan to release itango 0.0.1 to PyPI?

Thanks to both!

**Comment by vxgmichel** [comment] 2016-09-22 09:44
> This won't be true, since you are dropping the support.

Yes, I think the recommendation is cleaner this way: either use tango8 and the itango compatibility package, or tango9 and the latest itango package.

> when do you plan to release itango 0.0.1 to PyPI?

I can do it now, since we all agreed.

Thanks!

**Comment by reszelaz** [comment] 2016-09-22 16:10
Perfect! I will start the Sardana hotfix release 2.1.1 now but I think it won't be ready before the next Monday-Tuesday. It is just that we would need the itango 0.0.1 before.

**Closed** 2016-09-23 07:39 UTC
